annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 0.13.9
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: MetalLB is a load-balancer implementation for bare metal Kubernetes clusters, using standard routing protocols.
home: https://github.com/bitnami/charts/tree/main/bitnami/metallb
icon: https://bitnami.com/assets/stacks/metallb-speaker/img/metallb-speaker-stack-220x234.png
keywords:
  - load-balancer
  - balancer
  - lb
  - bgp
  - arp
  - vrrp
  - vip
kubeVersion: ">= 1.19.0-0"
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: metallb
sources:
  - https://github.com/metallb/metallb
  - https://github.com/bitnami/containers/tree/main/bitnami/metallb
  - https://metallb.universe.tf
version: 4.3.0
